packages:
  - frontend
  - tests
  - email-templates

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

overrides:
  devalue: ^5.3.2
  validator: ^13.15.20
  '@lezer/common': 1.3.0
