root = "."
tmp_dir = ".bin"

[build]
  bin = "./.bin/arcane"
  cmd = "CGO_ENABLED=1 go build -tags 'exclude_frontend playwright' -o ./.bin/arcane ./cmd"
  exclude_dir = [".bin", "data"]
  stop_on_error = true
  delay = 1000
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "2s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true