FROM alpine:3

ARG TARGETARCH
ARG VERSION="dev"
ARG REVISION="unknown"

WORKDIR /app
RUN apk upgrade && apk --no-cache add ca-certificates tzdata curl gcompat
RUN mkdir -p /app/data

COPY ./backend/.bin/arcane-agent-linux-${TARGETARCH} ./arcane-agent

ENV ENVIRONMENT=production \
    AGENT_MODE=true \
    GIN_MODE=release \
    PORT=3553

LABEL org.opencontainers.image.authors="OFKM Technologies" \
    org.opencontainers.image.url="https://github.com/getarcaneapp/arcane" \
    org.opencontainers.image.documentation="https://github.com/getarcaneapp/arcane/blob/main/README.md" \
    org.opencontainers.image.source="https://github.com/getarcaneapp/arcane" \
    org.opencontainers.image.version=${VERSION} \
    org.opencontainers.image.revision=${REVISION} \
    org.opencontainers.image.licenses="BSD-3-Clause" \
    org.opencontainers.image.ref.name="arcane-agent" \
    org.opencontainers.image.title="Arcane Agent" \
    org.opencontainers.image.description="Arcane Agent" \
    com.ofkm.arcane.updater="false" \
    com.ofkm.arcane.server="true"

EXPOSE 3553
VOLUME ["/app/data"]

CMD ["./arcane-agent"]