services:
  arcane-agent:
    build:
      context: .
      dockerfile: Dockerfile-agent-distroless-static
    image: arcane-agent:distroless-static
    environment:
      - AGENT_MODE=true
      - PORT=3553
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-kqRNG7bBrN9e7lagJbEkv4Zj3kA8qShQZgBok5X+h6g=}
      - AGENT_TOKEN=replace-with-agent-token
      # or: - AGENT_BOOTSTRAP_TOKEN=pair-me
    ports:
      - '3553:3553'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent-data:/app/data
    user: '65532:65532'
    # Ensure socket access:
    # Linux: export DOCKER_SOCK_GID=$(stat -c '%g' /var/run/docker.sock)
    # macOS Desktop: usually 0
    group_add:
      - '${DOCKER_SOCK_GID:-0}'
    restart: unless-stopped
