services:
  arcane-agent:
    image: ghcr.io/ofkm/arcane-agent:latest
    container_name: arcane-agent-gpu-nvidia
    ports:
      - "3553:3553"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent-data:/app/data
    environment:
      - PUID=1000
      - PGID=1000
      - AGENT_MODE=true
      - AGENT_BOOTSTRAP_TOKEN=your-secure-token-here
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3552/api/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    restart: unless-stopped

volumes:
  agent-data:
