name: Build Next Image (Agent)

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'frontend/package.json'
  workflow_dispatch:

concurrency:
  group: build-agent-next
  cancel-in-progress: true

jobs:
  build-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: backend/go.mod

      - name: Set DOCKER_IMAGE_NAME
        run: |
          REPO_OWNER=${{ github.repository_owner }}
          DOCKER_IMAGE_NAME="ghcr.io/${REPO_OWNER,,}/arcane-headless"
          echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}" >>${GITHUB_ENV}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build agent binaries
        run: bash scripts/development/build-binaries.sh --docker --agent

      - name: Build and push agent image
        id: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile-agent-static
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:next

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: '${{ env.DOCKER_IMAGE_NAME }}'
          subject-digest: ${{ steps.build-push-image.outputs.digest }}
          push-to-registry: true
