name: Playwright E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            tests/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-universal
          restore-keys: |
            playwright-browsers-universal

      - name: Create Docker volumes for tests
        run: |
          docker volume create my-app-data || true
          docker volume create cache || true

      - name: Install test dependencies
        working-directory: tests
        run: npm ci

      - name: Install Playwright browsers
        working-directory: tests
        run: npx playwright install --with-deps

      - name: Run Playwright E2E tests
        working-directory: tests
        run: npx playright test

      - name: List Playwright report directory
        if: always()
        working-directory: tests
        run: ls -lR .report || echo "No report directory found in tests/.report"

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/.report
          include-hidden-files: true
