name: Playwright E2E Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/**'

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  build:
    timeout-minutes: 20
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export Arcane image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: false
          tags: arcane:playwright-tests
          build-args: BUILD_TAGS=playwright
          outputs: type=docker,dest=/tmp/arcane-image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: arcane-image
          path: /tmp/arcane-image.tar
          retention-days: 1

  test:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        database:
          - name: sqlite
            compose_file: setup/compose.yaml
            port: 3000
          - name: postgres
            compose_file: setup/compose-postgres.yaml
            port: 3001
    name: E2E Tests (${{ matrix.database.name }})
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Create Docker Test Resources
        run: |
          docker volume create my-app-data || true
          docker volume create cache || true
          docker network create my-test-network || true

      - name: Download Arcane Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: arcane-image
          path: /tmp

      - name: Load Arcane Docker image
        run: docker load -i /tmp/arcane-image.tar

      - name: Cache test images
        uses: actions/cache@v4
        id: test-images-cache
        with:
          path: /tmp/test-images.tar
          key: test-images-${{ runner.os }}-latest

      - name: Pull and save test images
        if: steps.test-images-cache.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/linuxserver/nginx:latest
          docker pull ghcr.io/linuxserver/radarr:nightly
          docker save ghcr.io/linuxserver/nginx:latest ghcr.io/linuxserver/radarr:nightly > /tmp/test-images.tar

      - name: Load test images from cache
        if: steps.test-images-cache.outputs.cache-hit == 'true'
        run: docker load < /tmp/test-images.tar

      - name: Install test dependencies
        run: pnpm --filter arcane-tests install

      - name: Install Playwright Browsers
        working-directory: ./tests
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm dlx playwright install --with-deps chromium

      - name: Run Playwright E2E tests
        run: pnpm --filter arcane-tests test
        env:
          COMPOSE_FILE: ${{ matrix.database.compose_file }}
          BASE_URL: http://localhost:${{ matrix.database.port }}

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.database.name }}
          path: tests/.report
          include-hidden-files: true
          retention-days: 15
