name: Svelte Check

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/type-check.yml'
      - '.github/svelte-check-matcher.json'
      - 'package.json'
      - 'bun.lock'
      - 'tsconfig.json'
      - 'svelte.config.js'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/type-check.yml'
      - '.github/svelte-check-matcher.json'
      - 'package.json'
      - 'bun.lock'
      - 'tsconfig.json'
      - 'svelte.config.js'
  workflow_dispatch:

jobs:
  type-check:
    name: Run Svelte Check
    # Don't run on dependabot branches
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Add svelte-check problem matcher
        run: echo "::add-matcher::.github/svelte-check-matcher.json"

      - name: Run svelte-check via bun script
        run: bun run check
